# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: admin.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61\x64min.proto\x12\x08modelbox\x1a\x1fgoogle/protobuf/timestamp.proto\"+\n\x08NodeInfo\x12\x11\n\thost_name\x18\x01 \x01(\t\x12\x0c\n\x04\x61rch\x18\x02 \x01(\t\"\\\n\x10HeartbeatRequest\x12 \n\x04node\x18\x01 \x01(\x0b\x32\x12.modelbox.NodeInfo\x12&\n\x02\x61t\x18\x14 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x13\n\x11HeartbeatResponse\"`\n\x15SubscribeEventRequest\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\x14\n\x0cml_framework\x18\x02 \x01(\t\x12\r\n\x05owner\x18\x03 \x01(\t\x12\x0f\n\x07\x61\x63tions\x18\x04 \x03(\t\"\x16\n\x14RegisterAgentRequest\"\x17\n\x15RegisterAgentResponse\"\x10\n\x0eGetWorkRequest\"\x11\n\x0fGetWorkResponse\"\x1b\n\x19UpdateActionStatusRequest\"\x1c\n\x1aUpdateActionStatusResponse2\xc8\x02\n\rModelBoxAdmin\x12P\n\rRegisterAgent\x12\x1e.modelbox.RegisterAgentRequest\x1a\x1f.modelbox.RegisterAgentResponse\x12\x44\n\tHeartbeat\x12\x1a.modelbox.HeartbeatRequest\x1a\x1b.modelbox.HeartbeatResponse\x12>\n\x07GetWork\x12\x18.modelbox.GetWorkRequest\x1a\x19.modelbox.GetWorkResponse\x12_\n\x12UpdateActionStatus\x12#.modelbox.UpdateActionStatusRequest\x1a$.modelbox.UpdateActionStatusResponseB-Z+github.com/tensorland/modelbox/sdk-go/protob\x06proto3')



_NODEINFO = DESCRIPTOR.message_types_by_name['NodeInfo']
_HEARTBEATREQUEST = DESCRIPTOR.message_types_by_name['HeartbeatRequest']
_HEARTBEATRESPONSE = DESCRIPTOR.message_types_by_name['HeartbeatResponse']
_SUBSCRIBEEVENTREQUEST = DESCRIPTOR.message_types_by_name['SubscribeEventRequest']
_REGISTERAGENTREQUEST = DESCRIPTOR.message_types_by_name['RegisterAgentRequest']
_REGISTERAGENTRESPONSE = DESCRIPTOR.message_types_by_name['RegisterAgentResponse']
_GETWORKREQUEST = DESCRIPTOR.message_types_by_name['GetWorkRequest']
_GETWORKRESPONSE = DESCRIPTOR.message_types_by_name['GetWorkResponse']
_UPDATEACTIONSTATUSREQUEST = DESCRIPTOR.message_types_by_name['UpdateActionStatusRequest']
_UPDATEACTIONSTATUSRESPONSE = DESCRIPTOR.message_types_by_name['UpdateActionStatusResponse']
NodeInfo = _reflection.GeneratedProtocolMessageType('NodeInfo', (_message.Message,), {
  'DESCRIPTOR' : _NODEINFO,
  '__module__' : 'admin_pb2'
  # @@protoc_insertion_point(class_scope:modelbox.NodeInfo)
  })
_sym_db.RegisterMessage(NodeInfo)

HeartbeatRequest = _reflection.GeneratedProtocolMessageType('HeartbeatRequest', (_message.Message,), {
  'DESCRIPTOR' : _HEARTBEATREQUEST,
  '__module__' : 'admin_pb2'
  # @@protoc_insertion_point(class_scope:modelbox.HeartbeatRequest)
  })
_sym_db.RegisterMessage(HeartbeatRequest)

HeartbeatResponse = _reflection.GeneratedProtocolMessageType('HeartbeatResponse', (_message.Message,), {
  'DESCRIPTOR' : _HEARTBEATRESPONSE,
  '__module__' : 'admin_pb2'
  # @@protoc_insertion_point(class_scope:modelbox.HeartbeatResponse)
  })
_sym_db.RegisterMessage(HeartbeatResponse)

SubscribeEventRequest = _reflection.GeneratedProtocolMessageType('SubscribeEventRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBEEVENTREQUEST,
  '__module__' : 'admin_pb2'
  # @@protoc_insertion_point(class_scope:modelbox.SubscribeEventRequest)
  })
_sym_db.RegisterMessage(SubscribeEventRequest)

RegisterAgentRequest = _reflection.GeneratedProtocolMessageType('RegisterAgentRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERAGENTREQUEST,
  '__module__' : 'admin_pb2'
  # @@protoc_insertion_point(class_scope:modelbox.RegisterAgentRequest)
  })
_sym_db.RegisterMessage(RegisterAgentRequest)

RegisterAgentResponse = _reflection.GeneratedProtocolMessageType('RegisterAgentResponse', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERAGENTRESPONSE,
  '__module__' : 'admin_pb2'
  # @@protoc_insertion_point(class_scope:modelbox.RegisterAgentResponse)
  })
_sym_db.RegisterMessage(RegisterAgentResponse)

GetWorkRequest = _reflection.GeneratedProtocolMessageType('GetWorkRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETWORKREQUEST,
  '__module__' : 'admin_pb2'
  # @@protoc_insertion_point(class_scope:modelbox.GetWorkRequest)
  })
_sym_db.RegisterMessage(GetWorkRequest)

GetWorkResponse = _reflection.GeneratedProtocolMessageType('GetWorkResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETWORKRESPONSE,
  '__module__' : 'admin_pb2'
  # @@protoc_insertion_point(class_scope:modelbox.GetWorkResponse)
  })
_sym_db.RegisterMessage(GetWorkResponse)

UpdateActionStatusRequest = _reflection.GeneratedProtocolMessageType('UpdateActionStatusRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEACTIONSTATUSREQUEST,
  '__module__' : 'admin_pb2'
  # @@protoc_insertion_point(class_scope:modelbox.UpdateActionStatusRequest)
  })
_sym_db.RegisterMessage(UpdateActionStatusRequest)

UpdateActionStatusResponse = _reflection.GeneratedProtocolMessageType('UpdateActionStatusResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEACTIONSTATUSRESPONSE,
  '__module__' : 'admin_pb2'
  # @@protoc_insertion_point(class_scope:modelbox.UpdateActionStatusResponse)
  })
_sym_db.RegisterMessage(UpdateActionStatusResponse)

_MODELBOXADMIN = DESCRIPTOR.services_by_name['ModelBoxAdmin']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z+github.com/tensorland/modelbox/sdk-go/proto'
  _NODEINFO._serialized_start=58
  _NODEINFO._serialized_end=101
  _HEARTBEATREQUEST._serialized_start=103
  _HEARTBEATREQUEST._serialized_end=195
  _HEARTBEATRESPONSE._serialized_start=197
  _HEARTBEATRESPONSE._serialized_end=216
  _SUBSCRIBEEVENTREQUEST._serialized_start=218
  _SUBSCRIBEEVENTREQUEST._serialized_end=314
  _REGISTERAGENTREQUEST._serialized_start=316
  _REGISTERAGENTREQUEST._serialized_end=338
  _REGISTERAGENTRESPONSE._serialized_start=340
  _REGISTERAGENTRESPONSE._serialized_end=363
  _GETWORKREQUEST._serialized_start=365
  _GETWORKREQUEST._serialized_end=381
  _GETWORKRESPONSE._serialized_start=383
  _GETWORKRESPONSE._serialized_end=400
  _UPDATEACTIONSTATUSREQUEST._serialized_start=402
  _UPDATEACTIONSTATUSREQUEST._serialized_end=429
  _UPDATEACTIONSTATUSRESPONSE._serialized_start=431
  _UPDATEACTIONSTATUSRESPONSE._serialized_end=459
  _MODELBOXADMIN._serialized_start=462
  _MODELBOXADMIN._serialized_end=790
# @@protoc_insertion_point(module_scope)
