# The storage system used for storing training artifacts
# This is optional if modelbox is started as a metadata service
blob_storage = "filesystem"

# Storage system used for storing metadata related to training artifacts
# such as models and checkpoints, and lineage of artifacts
metadata_storage = "integrated"

# Interface on which the metadata service is listening for network connections
listen_addr = ":8085"

# Additional configuration for filesystem based blob_storage
[blob_storage_filesystem]
base_dir = "/tmp/modelboxblobs"

# Additional configuration for integrated metadata storage
[metadata_storage_integrated]
path = "/tmp/modelbox.dat"

# Additional configuration for metadata storage in PostgreSQL
[metadata_storage_postgres]
host = "172.17.0.2"
port = 5432
user = "postgres"


[metadata_storage_mysql]
host     = "172.17.0.2"
port     = 3306
username = "root"
password = "foo"
dbname   = "modelbox"
