/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  docs:[
    'intro',
    'install',
    'compare',
    {
      type: 'category',
      label: 'Tutorials',

      link: {
        type: 'generated-index',
        description: "Tutorials for performing common use-cases with ModelBox",
      },
      collapsed: false,
      items: [
        'tutorials/log-metadata-pytorch',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      link: {
        type: 'generated-index',
        description: "In-depth guide to using and operating ModelBox",
      },
      collapsed: false,
      items: [
        'guides/concepts',
        'guides/configuration',
        'guides/experiments',
        'guides/metrics',
        'guides/models',
        'guides/model-distribution',
        'guides/tensorboard',
        'guides/python-sdk',
        'guides/cli',
        'guides/service-observability',
      ],
    },
  ],

  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
