//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "metrics")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub object_id: String,
    pub name: String,
    pub tensor: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub double_value: Option<f64>,
    pub step: Option<i64>,
    pub wall_clock: Option<TimeDateTime>,
    pub created_at: TimeDateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
