//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "mutations")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub object_id: String,
    pub object_type: i16,
    pub mutation_type: i16,
    pub namespace: String,
    pub experiment_payload: Option<Json>,
    pub model_payload: Option<Json>,
    pub model_version_payload: Option<Json>,
    pub created_at: TimeDateTime,
    pub processed_at: Option<TimeDateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
